#https://www.smarthomebeginner.com/docker-media-server-2024/
# roles/docker/tasks/main.yml
- name: Add user to Docker group
  become: true
  user:
    name: "{{ bootstrap_admin_user }}"
    groups: docker
    append: true
  tags: docker_group

- name: Create Docker directories with correct permissions
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(bootstrap_admin_user) }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0775') }}"
  loop:
    - { path: "{{ docker_root_folder }}" }
    - { path: "{{ docker_root_folder }}/appdata" }
    - { path: "{{ docker_root_folder }}/compose" }
    - { path: "{{ docker_root_folder }}/compose/udms" }
    - { path: "{{ docker_root_folder }}/logs" }
    - { path: "{{ docker_root_folder }}/scripts" }
    - { path: "{{ docker_root_folder }}/secrets", owner: 'root', group: 'root', mode: '0600' }
    - { path: "{{ docker_root_folder }}/shared" }
  tags: docker_directories

- name: Create .env file with permissions
  become: true
  file:
    path: "{{ docker_root_folder }}/.env"
    state: touch
    owner: root
    group: root
    mode: '0600'
  tags: docker_files

- name: Populate .env file
  become: true
  lineinfile:
    path: "{{ docker_root_folder }}/.env"
    create: yes
    line: "{{ item }}"
  with_items:
    - "PUID={{ PUID }}"
    - "PGID={{ PGID }}"
    - "TZ={{ TZ }}"
    - "USERDIR={{ USERDIR }}"
    - "DOCKERDIR={{ DOCKERDIR }}"
    - "DATADIR={{ DATADIR }}"
    - "HOSTNAME={{ HOSTNAME }}"
  tags: docker_files

- name: Create master Docker Compose file
  become: true
  file:
    path: "{{ docker_root_folder }}/docker-compose-udms.yml"
    state: touch
  tags: docker_files

- name: Install required packages and set permissions
  become: true
  block:
    - name: Install acl package
      apt:
        name: acl
        state: present
      tags: permissions

    - name: Set directory permissions
      file:
        path: "{{ docker_root_folder }}"
        mode: '0775'
      tags: permissions

    - name: Set default ACLs for Docker root folder
      acl:
        path: "{{ docker_root_folder }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: rwx
        state: present
        default: yes
      loop:
        - { entity: "{{ bootstrap_admin_user }}", etype: user }
        - { entity: docker, etype: group }
      tags: permissions

    - name: Set recursive ACLs for Docker root folder
      acl:
        path: "{{ docker_root_folder }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: rwx
        state: present
        recurse: yes
      loop:
        - { entity: "{{ bootstrap_admin_user }}", etype: user }
        - { entity: docker, etype: group }
      tags: permissions
